management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5555

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.glamrock: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul.ignored-services: "orgservice-new"

zuul:
  prefix:  /api
  routes:
    organizationservice: /organization/**
    licensingservice: /licensing/**
    licensingstatic:
      path: /licensestatic/**
      url: http://licenseservice-static-url:8081