#Setting the logging levels for the service
logging:
  level:
    root: DEBUG
    com.netflix: WARN
    org.springframework.web: WARN
    com.glamrock: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  servlet:
    contextPath:   /auth
